name: Django CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache:'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Check project
      run: |
        python manage.py check